version: '3.9'

services:
  lavalink:
    image: 'fredboat/lavalink'
    hostname: lavalinkserver
    networks:
      - music
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    environment:
      PORT: 2333
      PASSWORD: youshallnotpass
      MEMORY: 300M
    ports:
      - '2333:2333'
  app:
    container_name: DiscordBotComposeDev
    networks:
      - music
    image: discordbot:latest
    restart: on-failure
    volumes:
      - .:/src
networks:
  music: