version:  "3.9"

services:
  lavalink:
    image: "fredboat/lavalink"
    network_mode: host
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333
  app:
    container_name: DiscordBotComposeDev
    image: discordbot:latest
    restart: on-failure
    network_mode: host
    volumes:
      - .:/src